spring.application.name=chatapp

server.port=${PORT:8080}

# Allow external access
server.address=0.0.0.0

#spring.datasource.url=jdbc:mysql://localhost:3306/chat_app
#spring.datasource.username=root
#spring.datasource.password=N@vin1995

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7587vk50q8c739v1cv0-a.singapore-postgres.render.com:5432/chatdb_dkgq
spring.datasource.username=chatuser
spring.datasource.password=X7HTcuYyvSjBMoZKZOLZ3myMS2KN6qfH

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.dynamic=true

#I received a message, but I don?t trust this class. I won?t deserialize it. To avoid it in practice we added below line
spring.amqp.deserialization.trust.all=true

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit=DEBUG
